apiVersion: v1
kind: Service
metadata:
  name: devops-production-platform
spec:
  type: NodePort

  selector:
    app: devops-production-platform

  ports:
    - port: http
      targetPort: 3000
      nodePort: 30080
